{{- if .Values.secret.create -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.fullname }}-secrets
  namespace: {{ .Values.namespace }}
  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  encryptedData:
  {{- range $key, $value := .Values.secret.encryptedData }}
    {{ $key }}: {{ $value }}
  {{- end }}
  template:
    metadata:
      name: {{ .Values.fullname }}-secrets
      namespace: {{ .Values.namespace }}
    type: Opaque
{{- end }}  